name: Run Firebase Task

# The workflow triggers every time code is pushed to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step to pull down your code repository onto the runner machine
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # Step utilizing a saved secret as an environment variable
      - name: Execute Firebase JavaScript File
        # Inject the GitHub Secret into the process.env context
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: node firebase-init.js
